version: '2'
services:
  swarm:
    build: .
    command: ["/app/start.sh", "-r ${REPO}", "-c ${CHECKOUT}", "-n ${NODES}", "-e ${ENS}"]
    networks:
      - swarm_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8500"
      - "8545"
      - "8546"
      - "30399"
      - "30301"
      - "30303"
networks:
  swarm_network:
    driver: bridge
